#get categories
GET  http://localhost:3000/api/category HTTP/1.1

#edit article
PUT  http://localhost:3000/api/articles/mRsziN HTTP/1.1
content-type: application/json

{
  "name": "sample",
  "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
#delete article
DELETE  http://localhost:3000/api/articles/mRsziN HTTP/1.1

###
#delete comment
DELETE  http://localhost:3000/api/articles/mRsziN/comments/WGYJ1b HTTP/1.1

###
#add comment
POST  http://localhost:3000/api/articles/mRsziN/comments HTTP/1.1
content-type: application/json

{
  "name": "sample",
  "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
